#ifndef SQLPAGECONTROLEUI_GLOBAL_H
#define SQLPAGECONTROLEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SQLPAGECONTROLEUI_LIBRARY)
#  define SQLPAGECONTROLEUI_EXPORT Q_DECL_EXPORT
#else
#  define SQLPAGECONTROLEUI_EXPORT Q_DECL_IMPORT
#endif

#endif // SQLPAGECONTROLEUI_GLOBAL_H
