#ifndef EMPLOYEEMANAGER_GLOBAL_H
#define EMPLOYEEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EMPLOYEEMANAGER_LIBRARY)
#  define EMPLOYEEMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define EMPLOYEEMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // EMPLOYEEMANAGER_GLOBAL_H
